# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20170714_2257'),
        ('rango', '0004_auto_20170714_1916'),
    ]

    operations = [
    ]
